import { createContext, useContext, useState } from "react";

export type Language = "en" | "hi" | "hl";

export const LANGUAGE_NAMES: Record<Language, string> = {
  en: "English",
  hi: "हिंदी",
  hl: "Hinglish",
};

const T = {
  en: {
    // Nav / menu
    home: "Home",
    myCredits: "My Credits",
    editProfile: "Edit Profile",
    myProfile: "My Profile",
    searchProviders: "Search Providers",
    recruitment: "Recruitment",
    subscriptions: "Subscriptions",
    aboutUs: "About Us",
    terms: "Terms & Conditions",
    contactUs: "Contact Us",
    contactUsTitle: "Get in touch",
    contactUsSubtitle: "Tap any email to open your mailbox",
    mailHelp: "Help & Support",
    mailContact: "General Inquiries",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    logout: "Logout",
    loginSignup: "Login / Sign Up",
    language: "Language",
    dashboard: "Dashboard",
    callHistory: "Call History",
    notifications: "Notifications",
    noNotifications: "No notifications yet",
    noNotificationsHint: "When customers call you, they'll show up here",
    buyCredits: "Buy Credits",
    installApp: "Install App",
    coAdminLogin: "Staff Login",

    // Search
    searchPlaceholder: "Search by name, service, tags...",
    phoneSearchPlaceholder: "Enter mobile number...",
    searchBtn: "Search",
    searching: "Searching...",
    byNameService: "Name / Service",
    byMobile: "Mobile Number",
    currentLocation: "Current Location",
    customLocation: "Custom Location",
    enterAddress: "Enter your area / address...",
    useGps: "Use GPS",
    confirmLocation: "Confirm",
    popularServices: "Popular Services",
    noResults: "No providers found",
    noResultsHint: "Try a different search or expand your area",

    // Provider card
    approx: "Approx",
    away: "away",
    distanceUnknown: "Distance unknown",
    callNow: "Call",
    hidden: "Hidden",
    credits: "Credits",

    // Jobs
    jobs: "Jobs",
    postJob: "Post a Job",
    findJob: "Find Jobs",
    myPosts: "My Posts",
    jobMenuSubtitle: "Post or find jobs",
    jobPostDesc: "Post a job for 25 credits",
    jobFindDesc: "Call any job — 1 credit per call",
    jobMyPostsDesc: "View or delete your job posts",
    jobName: "Job Title",
    jobDesc: "Job Description",
    jobLocation: "Location",
    jobSalary: "Salary",
    jobHours: "Work Hours",
    jobPhone: "Contact Phone",
    postJobBtn: "Post Job (25 Credits)",
    confirmPost: "I confirm this is a real job post",
    noJobs: "No jobs posted yet",
    myPostsEmpty: "You haven't posted any jobs yet",
    deleteJob: "Delete",
    jobPostedOn: "Posted on",

    // Common
    cancel: "Cancel",
    submit: "Submit",
    loading: "Loading...",
    close: "Close",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    remove: "Remove",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    done: "Done",

    // Login prompt
    loginRequired: "Login Required",
    loginRequiredDesc: "Please login to make calls or post jobs",
    loginBtn: "Login",
    createAccount: "Create New Account",
    later: "Later",

    // Provider detail modal
    aboutSection: "About",
    chargeSection: "Approx Charge",
    distanceSection: "Distance",
    servicesSection: "Services",
    callBtn: "Call Now",
    connectingCall: "Connecting...",
    creditDeduct: "1 credit will be deducted per call",
    numberHidden: "Number hidden — Provider has hidden their contact",
    creditsFinished: "Credits finished — Cannot call",
    noNumber: "No number available",

    // Provider dashboard
    totalCredits: "Total Credits",
    totalCalls: "Total Calls",
    shareProfile: "Share Profile",
    copyLink: "Copy Link",
    callsReceived: "Calls Received",
    callsMade: "Calls Made",
    statsThisMonth: "This month",
    profileHidden: "Profile Hidden",
    profileVisible: "Profile Visible",
    hiddenInfo: "Your contact is hidden from customers",
    visibleInfo: "Customers can see and call you",
    hiddenWarning: "Your contact number will not be visible to anyone",

    // Credits
    freeCredits: "Free Credits",
    purchasedCredits: "Purchased Credits",
    creditsBalance: "Credits Balance",
    buyMore: "Buy More",
    promoCode: "Promo Code",
    applyPromo: "Apply",

    // Auth pages
    loginTitle: "Welcome Back",
    signupTitle: "Create Account",
    forgotPassword: "Forgot Password",
    sendOtp: "Send OTP",
    verifyOtp: "Verify & Login",
    resendOtp: "Resend OTP",
    orSignWith: "Or sign in with",
    noAccount: "Don't have an account? Sign Up",
    haveAccount: "Already have an account? Login",
    skipForNow: "Skip Login",
    googleLogin: "Continue with Google",

    // Provider setup form
    yourName: "Your Name",
    serviceName: "Service Name",
    description: "Description",
    tags: "Tags",
    serviceArea: "Service Area Address",

    // Notifications / toasts
    callFailed: "Call failed",
    noCreditMsg: "Buy credits to make calls",
    locationSet: "Location set",
    locationFailed: "Location not found",
    copiedLink: "Link copied!",
    loggedOut: "Logged out",

    // Double-charge calling
    doubleChargeBadge: "Double charge",
    forceCallingTitle: "Force Calling",
    forceCallingHint: "Allow calls from customers who have 0 credits. You'll pay 2 credits per such call.",
    forceCallingConfirmTitle: "Turn on Force Calling?",
    forceCallingConfirmBody: "When a 0-balance customer calls you, 2 credits will be deducted from your account (yours + customer's). Continue?",
    lowBalanceWarningTitle: "Provider has no balance",
    lowBalanceWarningBody: "{name}'s account has no balance. If you call now, 2 credits will be deducted from your account.",
    callTwoCredits: "Call (2 credits)",
    bothNoBalance: "Call not possible — both accounts have zero balance.",
    customerNoBalanceBlocked: "You don't have credits and the provider hasn't enabled zero-balance calls.",
    capReached: "Provider has hit today's limit for zero-balance calls.",
    needTwoCredits: "You need at least 2 credits to call this provider.",
    creditsCharged: "{n} credits deducted",
    callReasonNormal: "Normal",
    callReasonCustomerNoBalance: "Customer was low — you paid 2",
    callReasonProviderNoBalance: "Provider was low — you paid 2",
    lowBalanceBannerProvider: "Your balance is empty. Recharge or you'll keep losing leads.",
    rechargeNow: "Recharge now",

    // Subscriptions page
    subTitle: "Subscriptions",
    subBoost: "Boost",
    subPro: "Pro",
    subPremium: "Premium",
    subBoostTagline: "Get noticed in search",
    subProTagline: "Receive calls for free",
    subPremiumTagline: "Free Call — incoming and outgoing",
    subMonthly: "Monthly",
    subYearly: "Yearly",
    subSave: "Save",
    subSubscribe: "Subscribe",
    subRenew: "Renew / Extend",
    subUpgrade: "Upgrade",
    subSwitch: "Switch",
    subActiveBadge: "Active",
    subActiveLabel: "active",
    subDayRemaining: "day remaining",
    subDaysRemaining: "days remaining",
    subEnds: "ends",
    subPerMonth: "/month",
    subPerYearMo: "/mo",
    subHistory: "Subscription history",
    subAdminGranted: "admin granted",
    subFooter: "Subscriptions are one-time payments — no auto-renewal. Upgrade replaces your active plan.",
    subPaymentError: "Could not start payment",
    subPaymentErrorDesc: "Please try again.",

    // About page
    aboutPageTitle: "About Mitrify",
    aboutPageTagline: "Fast Service, Instant Connect",
    aboutOurTeamBtn: "Our Team",

    // Our Team page
    ourTeamTitle: "Our Team",
    ourTeamSubtitle: "Mitrify's talented members",
    ourTeamAdd: "Add Team Member",
    ourTeamComing: "Team members coming soon...",

    // Investment page
    investTitle: "Investment / Fund",
    investSubtitle: "Contact our founder",
    investFounderRole: "Founder & Developer",
    investEmailLabel: "Email",
    investMobile1: "Mobile 1",
    investMobile2: "Mobile 2",
    investLocationLabel: "Location",
    investLocationValue: "District Budaun, Uttar Pradesh, India",
    investCta: "Feel free to reach out for investment opportunities and partnerships!",

    // Signup page
    signupSubtitle: "Join Mitrify to find or offer services",
    signupContinueGoogle: "Continue with Google",
    signupOrMobile: "or sign up with mobile OTP",
    signupSecurityNote: "Mobile number verification is required for account security",
    signupMobileLabel: "Mobile Number",
    signupMobileHint: "Include country code, e.g. +91 for India",
    signupSendOtp: "Send OTP",
    signupOtpSentTitle: "OTP Sent",
    signupSendingTo: "Sending OTP to",
    signupSentTo: "Verification code sent to",
    signupEnterOtp: "Enter 6-digit OTP",
    signupVerifying: "Verifying...",
    signupVerifyOtp: "Verify OTP",
    signupChangeResend: "Change Number / Resend OTP",
    signupVerifiedOk: "verified successfully",
    signupUsernameLabel: "Username",
    signupUsernamePh: "Choose a username",
    signupSuggested: "Suggested usernames:",
    signupPwLabel: "Password",
    signupPwPh: "Create a password",
    signupConfirmPwLabel: "Confirm Password",
    signupConfirmPwPh: "Confirm your password",
    signupCreating: "Creating Account...",
    signupCreateBtn: "Create Account",
    signupAlreadyHave: "Already have an account? Login",
    signupOtpSentToast: "OTP sent to your mobile",
    signupOtpFailToast: "Failed to send OTP",
    signupTooMany: "Too many attempts. Please try again later.",
    signupInvalidNumber: "Invalid number. Use format: +91XXXXXXXXXX",
    signupMobileRequired: "Mobile number required",
    signupEnter6Otp: "Enter 6-digit OTP",
    signupServerVerifyFail: "Server verification failed",
    signupMobileVerified: "Mobile verified!",
    signupInvalidOtp: "Invalid OTP. Please check and try again.",
    signupOtpExpired: "OTP expired. Please request a new one.",
    signupVerifyFail: "Verification failed",
    signupUserPwRequired: "Username and password required",
    signupPwMismatch: "Passwords don't match",
    signupPwLen: "Password must be at least 4 characters",
    signupRegFail: "Registration failed",
    signupAccountCreated: "Account created successfully!",

    // Forgot password page
    forgotTitle: "Reset Password",
    forgotSubtitle: "Verify your phone number to reset password",
    forgotPhoneLabel: "Registered Mobile Number",
    forgotSendingOtp: "Sending OTP...",
    forgotOtpSentTo: "OTP sent to",
    forgotOtpLabel: "Enter OTP",
    forgotOtpPh: "Enter 6-digit OTP",
    forgotNewPwLabel: "New Password",
    forgotNewPwPh: "Enter new password",
    forgotResetting: "Resetting...",
    forgotResetBtn: "Reset Password",
    forgotResendBtn: "Resend OTP",
    forgotBackToLogin: "Back to Login",
    forgotOtpSentToast: "OTP sent to your phone",
    forgotPhoneRequired: "Phone number required",
    forgotEnterOtp: "Please enter OTP",
    forgotPwLen: "Password must be at least 4 characters",
    forgotResetFail: "Reset failed",
    forgotResetOk: "Password reset successfully! Please login.",

    // Select role
    selectRoleSettingUp: "Setting up your account...",

    // Customer setup
    setupTitle: "Complete Your Profile",
    setupSubtitle: "Set up your customer account",
    setupNameLabel: "Full Name *",
    setupNamePh: "Your name",
    setupMobiles: "Mobile Numbers",
    setupAddMobile: "Add Mobile Number",
    setupAddOther: "Add Other Number",
    setupSendOtp: "Send OTP",
    setupSendingOtp: "Sending OTP...",
    setupSentOtpTo: "OTP sent to",
    setupVerify: "Verify",
    setupReferralLabel: "Referral Code (optional)",
    setupReferralPh: "Enter promo code",
    setupSettingUp: "Setting up...",
    setupGetStarted: "Get Started",
    setupNameRequired: "Name required",
    setupSetupFail: "Setup failed",
    setupTryAgain: "Please try again",
    setupPromoApplied: "Promo code applied!",
    setupPromoInvalid: "Promo code invalid",
    setupEnterMobile: "Enter a mobile number",
    setupNumberAlready: "Number already added",
    setupOtpSentTo: "OTP sent to",
    setupNumberVerified: "Number verified and added!",

    // Terms page
    termsPageTitle: "Terms & Conditions",
    termsPageSubtitle: "Terms & Conditions & Disclaimer",
    termsAboutLink: "About Us",

    // Not found
    nfTitle: "404 Page Not Found",
    nfDesc: "Did you forget to add the page to the router?",
  },

  hi: {
    // Nav / menu
    home: "होम",
    myCredits: "मेरे क्रेडिट",
    editProfile: "प्रोफ़ाइल बदलें",
    myProfile: "मेरी प्रोफ़ाइल",
    searchProviders: "सेवा प्रदाता खोजें",
    recruitment: "भर्ती",
    subscriptions: "सब्सक्रिप्शन",
    aboutUs: "हमारे बारे में",
    terms: "नियम व शर्तें",
    contactUs: "संपर्क करें",
    contactUsTitle: "हमसे संपर्क करें",
    contactUsSubtitle: "किसी भी ईमेल पर टैप करें — आपका मेल ऐप खुल जाएगा",
    mailHelp: "सहायता व सपोर्ट",
    mailContact: "सामान्य पूछताछ",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड",
    logout: "लॉगआउट",
    loginSignup: "लॉगिन / साइन अप",
    language: "भाषा",
    dashboard: "डैशबोर्ड",
    callHistory: "कॉल इतिहास",
    notifications: "सूचनाएं",
    noNotifications: "अभी कोई सूचना नहीं",
    noNotificationsHint: "जब ग्राहक आपको कॉल करेंगे, यहाँ दिखेगा",
    buyCredits: "क्रेडिट खरीदें",
    installApp: "ऐप इंस्टॉल करें",
    coAdminLogin: "स्टाफ लॉगिन",

    // Search
    searchPlaceholder: "नाम, सेवा, टैग से खोजें...",
    phoneSearchPlaceholder: "मोबाइल नंबर डालें...",
    searchBtn: "खोजें",
    searching: "खोज रहे हैं...",
    byNameService: "नाम / सेवा",
    byMobile: "मोबाइल नंबर",
    currentLocation: "वर्तमान स्थान",
    customLocation: "अन्य स्थान",
    enterAddress: "अपना क्षेत्र / पता डालें...",
    useGps: "GPS उपयोग करें",
    confirmLocation: "पुष्टि करें",
    popularServices: "लोकप्रिय सेवाएं",
    noResults: "कोई सेवा प्रदाता नहीं मिला",
    noResultsHint: "अलग खोज या बड़े क्षेत्र में खोजें",

    // Provider card
    approx: "अनुमानित",
    away: "दूर",
    distanceUnknown: "दूरी अज्ञात",
    callNow: "कॉल",
    hidden: "छुपाया",
    credits: "क्रेडिट",

    // Jobs
    jobs: "नौकरी",
    postJob: "नौकरी पोस्ट करें",
    findJob: "नौकरी खोजें",
    myPosts: "मेरी पोस्ट",
    jobMenuSubtitle: "नौकरी पोस्ट करें या खोजें",
    jobPostDesc: "25 क्रेडिट के लिए नौकरी पोस्ट करें",
    jobFindDesc: "कोई भी नौकरी पर कॉल करें — 1 क्रेडिट प्रति कॉल",
    jobMyPostsDesc: "अपनी नौकरी पोस्ट देखें या हटाएं",
    jobName: "नौकरी का नाम",
    jobDesc: "विवरण",
    jobLocation: "स्थान",
    jobSalary: "वेतन",
    jobHours: "काम के घंटे",
    jobPhone: "संपर्क नंबर",
    postJobBtn: "नौकरी पोस्ट करें (25 क्रेडिट)",
    confirmPost: "मैं पुष्टि करता/करती हूँ कि यह असली जॉब पोस्ट है",
    noJobs: "अभी कोई नौकरी नहीं",
    myPostsEmpty: "आपने अभी कोई नौकरी पोस्ट नहीं की",
    deleteJob: "हटाएं",
    jobPostedOn: "पोस्ट किया",

    // Common
    cancel: "रद्द करें",
    submit: "जमा करें",
    loading: "लोड हो रहा है...",
    close: "बंद करें",
    save: "सहेजें",
    delete: "हटाएं",
    edit: "बदलें",
    add: "जोड़ें",
    remove: "हटाएं",
    confirm: "पुष्टि करें",
    back: "वापस",
    next: "आगे",
    done: "हो गया",

    // Login prompt
    loginRequired: "लॉगिन आवश्यक है",
    loginRequiredDesc: "कॉल करने या नौकरी पोस्ट करने के लिए पहले लॉगिन करें",
    loginBtn: "लॉगिन करें",
    createAccount: "नया खाता बनाएं",
    later: "बाद में",

    // Provider detail modal
    aboutSection: "परिचय",
    chargeSection: "अनुमानित शुल्क",
    distanceSection: "दूरी",
    servicesSection: "सेवाएं",
    callBtn: "कॉल करें",
    connectingCall: "जोड़ रहे हैं...",
    creditDeduct: "कॉल पर 1 क्रेडिट कटेगा",
    numberHidden: "नंबर छुपाया है — प्रदाता ने संपर्क छुपाया है",
    creditsFinished: "क्रेडिट खत्म — कॉल नहीं हो सकती",
    noNumber: "कोई नंबर उपलब्ध नहीं",

    // Provider dashboard
    totalCredits: "कुल क्रेडिट",
    totalCalls: "कुल कॉल",
    shareProfile: "प्रोफ़ाइल शेयर करें",
    copyLink: "लिंक कॉपी करें",
    callsReceived: "प्राप्त कॉल",
    callsMade: "की गई कॉल",
    statsThisMonth: "इस महीने",
    profileHidden: "प्रोफ़ाइल छुपाई",
    profileVisible: "प्रोफ़ाइल दिखाई",
    hiddenInfo: "ग्राहक आपसे संपर्क नहीं कर सकते",
    visibleInfo: "ग्राहक आपको देख और कॉल कर सकते हैं",
    hiddenWarning: "आपका contact number किसी को नहीं दिखेगा",

    // Credits
    freeCredits: "मुफ्त क्रेडिट",
    purchasedCredits: "खरीदे क्रेडिट",
    creditsBalance: "क्रेडिट बैलेंस",
    buyMore: "और खरीदें",
    promoCode: "प्रोमो कोड",
    applyPromo: "लगाएं",

    // Auth pages
    loginTitle: "वापस स्वागत है",
    signupTitle: "खाता बनाएं",
    forgotPassword: "पासवर्ड भूल गए",
    sendOtp: "OTP भेजें",
    verifyOtp: "सत्यापित करें और लॉगिन",
    resendOtp: "OTP दोबारा भेजें",
    orSignWith: "या इससे साइन इन करें",
    noAccount: "खाता नहीं है? साइन अप करें",
    haveAccount: "खाता है? लॉगिन करें",
    skipForNow: "Skip Login",
    googleLogin: "Google से जारी रखें",

    // Provider setup form
    yourName: "आपका नाम क्या है",
    serviceName: "आप क्या काम करते हैं",
    description: "आपके काम के बारे में बताओ",
    tags: "टैग",
    serviceArea: "किस शहर में काम करते हैं",

    // Notifications
    callFailed: "कॉल विफल",
    noCreditMsg: "कॉल के लिए क्रेडिट खरीदें",
    locationSet: "स्थान सेट हो गया",
    locationFailed: "स्थान नहीं मिला",
    copiedLink: "लिंक कॉपी हो गया!",
    loggedOut: "लॉगआउट हो गए",

    // Double-charge calling
    doubleChargeBadge: "डबल चार्ज",
    forceCallingTitle: "फोर्स कॉलिंग",
    forceCallingHint: "0 बैलेंस वाले ग्राहकों की कॉल भी आ सकेगी। ऐसी हर कॉल पर 2 क्रेडिट आपके खाते से कटेंगे।",
    forceCallingConfirmTitle: "फोर्स कॉलिंग ON करें?",
    forceCallingConfirmBody: "जब भी कोई 0 बैलेंस वाला ग्राहक आपको कॉल करेगा, आपके खाते से 2 क्रेडिट (आपका + ग्राहक का) कट जाएंगे। जारी रखें?",
    lowBalanceWarningTitle: "प्रदाता के पास बैलेंस नहीं है",
    lowBalanceWarningBody: "{name} के खाते में बैलेंस नहीं है। अगर अभी कॉल करते हैं तो आपके खाते से 2 क्रेडिट कट जाएंगे।",
    callTwoCredits: "कॉल करें (2 क्रेडिट)",
    bothNoBalance: "कॉल संभव नहीं — दोनों खातों में बैलेंस खत्म है।",
    customerNoBalanceBlocked: "आपके पास क्रेडिट नहीं हैं और प्रदाता ने जीरो-बैलेंस कॉल चालू नहीं की है।",
    capReached: "इस प्रदाता की आज की जीरो-बैलेंस कॉल लिमिट पूरी हो गई है।",
    needTwoCredits: "इस प्रदाता को कॉल करने के लिए कम से कम 2 क्रेडिट चाहिए।",
    creditsCharged: "{n} क्रेडिट कटे",
    callReasonNormal: "सामान्य",
    callReasonCustomerNoBalance: "ग्राहक के पास बैलेंस नहीं था — आपने 2 दिए",
    callReasonProviderNoBalance: "प्रदाता के पास बैलेंस नहीं था — आपने 2 दिए",
    lowBalanceBannerProvider: "आपका बैलेंस खत्म है। रिचार्ज करें वरना आपकी कॉल कम होती जाएंगी।",
    rechargeNow: "अभी रिचार्ज करें",

    // Subscriptions page
    subTitle: "सब्सक्रिप्शन",
    subBoost: "बूस्ट",
    subPro: "प्रो",
    subPremium: "प्रीमियम",
    subBoostTagline: "खोज में दिखें",
    subProTagline: "मुफ्त कॉल पाएं",
    subPremiumTagline: "मुफ्त कॉल — आने और जाने वाली",
    subMonthly: "मासिक",
    subYearly: "वार्षिक",
    subSave: "बचत",
    subSubscribe: "सब्सक्राइब करें",
    subRenew: "रिन्यू / बढ़ाएं",
    subUpgrade: "अपग्रेड करें",
    subSwitch: "बदलें",
    subActiveBadge: "सक्रिय",
    subActiveLabel: "सक्रिय",
    subDayRemaining: "दिन शेष",
    subDaysRemaining: "दिन शेष",
    subEnds: "समाप्त",
    subPerMonth: "/महीना",
    subPerYearMo: "/महीना",
    subHistory: "सब्सक्रिप्शन इतिहास",
    subAdminGranted: "एडमिन ने दिया",
    subFooter: "सब्सक्रिप्शन एक बार का भुगतान है — ऑटो-रिन्यूअल नहीं। अपग्रेड करने पर आपका पुराना प्लान बदल जाएगा।",
    subPaymentError: "पेमेंट शुरू नहीं हो सका",
    subPaymentErrorDesc: "कृपया फिर कोशिश करें।",

    // About page
    aboutPageTitle: "Mitrify के बारे में",
    aboutPageTagline: "तेज़ सेवा, तुरंत संपर्क",
    aboutOurTeamBtn: "हमारी टीम",

    // Our Team page
    ourTeamTitle: "हमारी टीम",
    ourTeamSubtitle: "Mitrify के प्रतिभाशाली सदस्य",
    ourTeamAdd: "टीम सदस्य जोड़ें",
    ourTeamComing: "टीम के सदस्य जल्द ही...",

    // Investment page
    investTitle: "निवेश / फंड",
    investSubtitle: "हमारे संस्थापक से संपर्क करें",
    investFounderRole: "संस्थापक एवं डेवलपर",
    investEmailLabel: "ईमेल",
    investMobile1: "मोबाइल 1",
    investMobile2: "मोबाइल 2",
    investLocationLabel: "स्थान",
    investLocationValue: "जिला बदायूं, उत्तर प्रदेश, भारत",
    investCta: "निवेश और साझेदारी के लिए संपर्क करें!",

    // Signup page
    signupSubtitle: "सेवाएं खोजने या देने के लिए Mitrify में शामिल हों",
    signupContinueGoogle: "Google से जारी रखें",
    signupOrMobile: "या मोबाइल OTP से साइन अप करें",
    signupSecurityNote: "खाते की सुरक्षा के लिए मोबाइल नंबर सत्यापन ज़रूरी है",
    signupMobileLabel: "मोबाइल नंबर",
    signupMobileHint: "देश कोड लगाएं, जैसे भारत के लिए +91",
    signupSendOtp: "OTP भेजें",
    signupOtpSentTitle: "OTP भेजा गया",
    signupSendingTo: "OTP भेज रहे हैं",
    signupSentTo: "वेरिफिकेशन कोड भेजा गया",
    signupEnterOtp: "6 अंकों का OTP डालें",
    signupVerifying: "सत्यापित हो रहा है...",
    signupVerifyOtp: "OTP सत्यापित करें",
    signupChangeResend: "नंबर बदलें / OTP दोबारा भेजें",
    signupVerifiedOk: "सत्यापित हो गया",
    signupUsernameLabel: "यूज़रनेम",
    signupUsernamePh: "एक यूज़रनेम चुनें",
    signupSuggested: "सुझाए गए यूज़रनेम:",
    signupPwLabel: "पासवर्ड",
    signupPwPh: "पासवर्ड बनाएं",
    signupConfirmPwLabel: "पासवर्ड पक्का करें",
    signupConfirmPwPh: "पासवर्ड फिर से डालें",
    signupCreating: "खाता बना रहे हैं...",
    signupCreateBtn: "खाता बनाएं",
    signupAlreadyHave: "खाता है? लॉगिन करें",
    signupOtpSentToast: "OTP आपके मोबाइल पर भेज दिया",
    signupOtpFailToast: "OTP भेजने में विफल",
    signupTooMany: "बहुत बार कोशिश की। कुछ देर बाद फिर कोशिश करें।",
    signupInvalidNumber: "गलत नंबर। फॉर्मेट: +91XXXXXXXXXX",
    signupMobileRequired: "मोबाइल नंबर आवश्यक है",
    signupEnter6Otp: "6 अंकों का OTP डालें",
    signupServerVerifyFail: "सर्वर सत्यापन विफल",
    signupMobileVerified: "मोबाइल सत्यापित!",
    signupInvalidOtp: "गलत OTP। कृपया दोबारा देखें।",
    signupOtpExpired: "OTP समाप्त। नया OTP मांगें।",
    signupVerifyFail: "सत्यापन विफल",
    signupUserPwRequired: "यूज़रनेम और पासवर्ड आवश्यक है",
    signupPwMismatch: "पासवर्ड मेल नहीं खाते",
    signupPwLen: "पासवर्ड कम से कम 4 अक्षर का हो",
    signupRegFail: "रजिस्ट्रेशन विफल",
    signupAccountCreated: "खाता सफलतापूर्वक बना!",

    // Forgot password page
    forgotTitle: "पासवर्ड रीसेट करें",
    forgotSubtitle: "पासवर्ड रीसेट करने के लिए अपना फोन सत्यापित करें",
    forgotPhoneLabel: "रजिस्टर्ड मोबाइल नंबर",
    forgotSendingOtp: "OTP भेज रहे हैं...",
    forgotOtpSentTo: "OTP भेजा गया",
    forgotOtpLabel: "OTP डालें",
    forgotOtpPh: "6 अंकों का OTP डालें",
    forgotNewPwLabel: "नया पासवर्ड",
    forgotNewPwPh: "नया पासवर्ड डालें",
    forgotResetting: "रीसेट हो रहा है...",
    forgotResetBtn: "पासवर्ड रीसेट करें",
    forgotResendBtn: "OTP दोबारा भेजें",
    forgotBackToLogin: "लॉगिन पर वापस",
    forgotOtpSentToast: "OTP आपके फोन पर भेज दिया",
    forgotPhoneRequired: "फोन नंबर आवश्यक है",
    forgotEnterOtp: "कृपया OTP डालें",
    forgotPwLen: "पासवर्ड कम से कम 4 अक्षर का हो",
    forgotResetFail: "रीसेट विफल",
    forgotResetOk: "पासवर्ड रीसेट हो गया! कृपया लॉगिन करें।",

    // Select role
    selectRoleSettingUp: "आपका खाता तैयार हो रहा है...",

    // Customer setup
    setupTitle: "अपनी प्रोफ़ाइल पूरी करें",
    setupSubtitle: "अपना ग्राहक खाता सेट करें",
    setupNameLabel: "पूरा नाम *",
    setupNamePh: "आपका नाम",
    setupMobiles: "मोबाइल नंबर",
    setupAddMobile: "मोबाइल नंबर जोड़ें",
    setupAddOther: "और नंबर जोड़ें",
    setupSendOtp: "OTP भेजें",
    setupSendingOtp: "OTP भेज रहे हैं...",
    setupSentOtpTo: "OTP भेजा गया",
    setupVerify: "सत्यापित करें",
    setupReferralLabel: "रेफरल कोड (वैकल्पिक)",
    setupReferralPh: "प्रोमो कोड डालें",
    setupSettingUp: "सेट हो रहा है...",
    setupGetStarted: "शुरू करें",
    setupNameRequired: "नाम आवश्यक है",
    setupSetupFail: "सेटअप विफल",
    setupTryAgain: "कृपया फिर कोशिश करें",
    setupPromoApplied: "प्रोमो कोड लागू हो गया!",
    setupPromoInvalid: "प्रोमो कोड गलत है",
    setupEnterMobile: "मोबाइल नंबर डालें",
    setupNumberAlready: "नंबर पहले से जोड़ा है",
    setupOtpSentTo: "OTP भेजा गया",
    setupNumberVerified: "नंबर सत्यापित हो गया!",

    // Terms page
    termsPageTitle: "नियम एवं शर्तें",
    termsPageSubtitle: "नियम, शर्तें व अस्वीकरण",
    termsAboutLink: "हमारे बारे में",

    // Not found
    nfTitle: "404 पेज नहीं मिला",
    nfDesc: "क्या आप राउटर में पेज जोड़ना भूल गए?",
  },

  hl: {
    // Nav / menu
    home: "Home",
    myCredits: "Mere Credits",
    editProfile: "Profile Edit Karo",
    myProfile: "Meri Profile",
    searchProviders: "Providers Dhundho",
    recruitment: "Recruitment",
    subscriptions: "Subscriptions",
    aboutUs: "Hamare Baare Mein",
    terms: "Terms & Conditions",
    contactUs: "Contact Us",
    contactUsTitle: "Humse Sampark Karein",
    contactUsSubtitle: "Kisi bhi email par tap karein — aapka mail app khul jayega",
    mailHelp: "Help & Support",
    mailContact: "General Inquiries",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    logout: "Logout",
    loginSignup: "Login / Sign Up",
    language: "Bhasha",
    dashboard: "Dashboard",
    callHistory: "Call History",
    notifications: "Notifications",
    noNotifications: "Abhi koi notification nahi",
    noNotificationsHint: "Jab customer aapko call karenge, yahan dikhenge",
    buyCredits: "Credits Kharido",
    installApp: "App Install Karo",
    coAdminLogin: "Staff Login",

    // Search
    searchPlaceholder: "Naam, service, tags se dhundho...",
    phoneSearchPlaceholder: "Mobile number daalo...",
    searchBtn: "Dhundho",
    searching: "Dhundh rahe hain...",
    byNameService: "Naam / Service",
    byMobile: "Mobile Number",
    currentLocation: "Current Location",
    customLocation: "Alag Location",
    enterAddress: "Apna area / address daalo...",
    useGps: "GPS Use Karo",
    confirmLocation: "Confirm Karo",
    popularServices: "Popular Services",
    noResults: "Koi provider nahi mila",
    noResultsHint: "Alag search karo ya area badhao",

    // Provider card
    approx: "Lagbhag",
    away: "door",
    distanceUnknown: "Doori pata nahi",
    callNow: "Call",
    hidden: "Hidden",
    credits: "Credits",

    // Jobs
    jobs: "Jobs",
    postJob: "Job Post Karo",
    findJob: "Job Dhundho",
    myPosts: "Meri Posts",
    jobMenuSubtitle: "Job post karo ya dhundho",
    jobPostDesc: "25 credits mein job post karo",
    jobFindDesc: "Kisi bhi job par call karo — 1 credit per call",
    jobMyPostsDesc: "Apni posted jobs dekho ya delete karo",
    jobName: "Job ka Naam",
    jobDesc: "Kaam ki detail",
    jobLocation: "Location",
    jobSalary: "Salary",
    jobHours: "Kaam ke Ghante",
    jobPhone: "Contact Number",
    postJobBtn: "Job Post Karein (25 Credits)",
    confirmPost: "Main confirm karta/karti hoon ki yeh real job post hai",
    noJobs: "Abhi koi job nahi hai",
    myPostsEmpty: "Aapne abhi koi job post nahi ki",
    deleteJob: "Delete",
    jobPostedOn: "Post ki",

    // Common
    cancel: "Cancel",
    submit: "Submit Karo",
    loading: "Load ho raha hai...",
    close: "Band Karo",
    save: "Save Karo",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    remove: "Hataao",
    confirm: "Confirm",
    back: "Wapas",
    next: "Aage",
    done: "Ho Gaya",

    // Login prompt
    loginRequired: "Login Zaruri Hai",
    loginRequiredDesc: "Call karne ya job post karne ke liye pehle login karo",
    loginBtn: "Login Karein",
    createAccount: "Naya Account Banao",
    later: "Baad Mein",

    // Provider detail modal
    aboutSection: "Baare Mein",
    chargeSection: "Lagbhag Charge",
    distanceSection: "Doori",
    servicesSection: "Services",
    callBtn: "Call Karein",
    connectingCall: "Connect ho raha hai...",
    creditDeduct: "Call karne par 1 credit deduct hoga",
    numberHidden: "Number hidden hai — Provider ne contact chupaaya hai",
    creditsFinished: "Credits khatam — Call nahi ho sakti",
    noNumber: "Koi number available nahi",

    // Provider dashboard
    totalCredits: "Total Credits",
    totalCalls: "Total Calls",
    shareProfile: "Profile Share Karo",
    copyLink: "Link Copy Karo",
    callsReceived: "Calls Received",
    callsMade: "Calls Made",
    statsThisMonth: "Is mahine",
    profileHidden: "Profile Hidden",
    profileVisible: "Profile Visible",
    hiddenInfo: "Customers aapko contact nahi kar sakte",
    visibleInfo: "Customers aapko dekh aur call kar sakte hain",
    hiddenWarning: "Aapka contact number kisiko nahi dikhega",

    // Credits
    freeCredits: "Free Credits",
    purchasedCredits: "Kharide Credits",
    creditsBalance: "Credits Balance",
    buyMore: "Aur Kharido",
    promoCode: "Promo Code",
    applyPromo: "Apply",

    // Auth pages
    loginTitle: "Wapas Aaye!",
    signupTitle: "Account Banao",
    forgotPassword: "Password Bhool Gaye",
    sendOtp: "OTP Bhejo",
    verifyOtp: "Verify Karo & Login",
    resendOtp: "OTP Dobara Bhejo",
    orSignWith: "Ya isse sign in karo",
    noAccount: "Account nahi hai? Sign Up Karo",
    haveAccount: "Account hai? Login Karo",
    skipForNow: "Skip Login",
    googleLogin: "Google se Continue Karo",

    // Provider setup form
    yourName: "Aapka Naam Kya Hai",
    serviceName: "Aap Kya Kaam Karte Hain",
    description: "Aapke Kaam Ke Baare Mein Batao",
    tags: "Tags",
    serviceArea: "Aap Kaha Kaam Karte Hain",

    // Notifications
    callFailed: "Call fail ho gayi",
    noCreditMsg: "Call ke liye credits kharido",
    locationSet: "Location set ho gayi",
    locationFailed: "Location nahi mili",
    copiedLink: "Link copy ho gaya!",
    loggedOut: "Logout ho gaye",

    // Double-charge calling
    doubleChargeBadge: "Double charge",
    forceCallingTitle: "Force Calling",
    forceCallingHint: "0 balance wale customers ki call bhi le sakte ho. Aisi har call pe aapke account se 2 credit kat jayenge.",
    forceCallingConfirmTitle: "Force Calling ON karein?",
    forceCallingConfirmBody: "Jab bhi koi 0 balance wala customer aapko call karega, aapke account se 2 credit (apna + customer ka) kat jayenge. Continue?",
    lowBalanceWarningTitle: "Provider ke paas balance nahi hai",
    lowBalanceWarningBody: "{name} ke account mein balance nahi hai. Agar abhi call karenge to aapke account se 2 credit kat jayenge.",
    callTwoCredits: "Call karein (2 credits)",
    bothNoBalance: "Call abhi possible nahi — dono ke account mein balance khatam hai.",
    customerNoBalanceBlocked: "Aapke paas credits nahi hain aur provider ne zero-balance calls allow nahi ki hain.",
    capReached: "Is provider ki aaj ki zero-balance call limit puri ho gayi hai.",
    needTwoCredits: "Is provider ko call karne ke liye kam se kam 2 credits chahiye.",
    creditsCharged: "{n} credits cut hue",
    callReasonNormal: "Normal",
    callReasonCustomerNoBalance: "Customer low tha — aapne 2 diye",
    callReasonProviderNoBalance: "Provider low tha — aapne 2 diye",
    lowBalanceBannerProvider: "Aapka balance khatam hai. Recharge karein varna calls aana band ho jayegi.",
    rechargeNow: "Abhi recharge karein",

    // Subscriptions page
    subTitle: "Subscriptions",
    subBoost: "Boost",
    subPro: "Pro",
    subPremium: "Premium",
    subBoostTagline: "Search mein dikho",
    subProTagline: "Free calls receive karo",
    subPremiumTagline: "Free Call — incoming aur outgoing",
    subMonthly: "Monthly",
    subYearly: "Yearly",
    subSave: "Bachat",
    subSubscribe: "Subscribe Karo",
    subRenew: "Renew / Extend",
    subUpgrade: "Upgrade Karo",
    subSwitch: "Switch Karo",
    subActiveBadge: "Active",
    subActiveLabel: "active",
    subDayRemaining: "din baaki",
    subDaysRemaining: "din baaki",
    subEnds: "khatam",
    subPerMonth: "/month",
    subPerYearMo: "/mo",
    subHistory: "Subscription history",
    subAdminGranted: "admin ne diya",
    subFooter: "Subscriptions ek-baar ka payment hai — auto-renewal nahi. Upgrade karne par purana plan replace ho jayega.",
    subPaymentError: "Payment shuru nahi ho saka",
    subPaymentErrorDesc: "Phir try karein.",

    // About page
    aboutPageTitle: "Mitrify ke Baare Mein",
    aboutPageTagline: "Fast Service, Instant Connect",
    aboutOurTeamBtn: "Hamari Team",

    // Our Team page
    ourTeamTitle: "Hamari Team",
    ourTeamSubtitle: "Mitrify ke talented members",
    ourTeamAdd: "Team Member Add Karo",
    ourTeamComing: "Team members jald hi...",

    // Investment page
    investTitle: "Investment / Fund",
    investSubtitle: "Founder se sampark karein",
    investFounderRole: "Founder & Developer",
    investEmailLabel: "Email",
    investMobile1: "Mobile 1",
    investMobile2: "Mobile 2",
    investLocationLabel: "Location",
    investLocationValue: "District Budaun, Uttar Pradesh, India",
    investCta: "Investment opportunities aur partnerships ke liye sampark karein!",

    // Signup page
    signupSubtitle: "Services dhundhne ya dene ke liye Mitrify join karein",
    signupContinueGoogle: "Google se Continue Karo",
    signupOrMobile: "ya mobile OTP se sign up karein",
    signupSecurityNote: "Account security ke liye mobile number verification zaruri hai",
    signupMobileLabel: "Mobile Number",
    signupMobileHint: "Country code lagayein, jaise India ke liye +91",
    signupSendOtp: "OTP Bhejo",
    signupOtpSentTitle: "OTP Bheja Gaya",
    signupSendingTo: "OTP bhej rahe hain",
    signupSentTo: "Verification code bheja gaya",
    signupEnterOtp: "6-digit OTP daalo",
    signupVerifying: "Verify ho raha hai...",
    signupVerifyOtp: "OTP Verify Karo",
    signupChangeResend: "Number Badlo / OTP Dobara Bhejo",
    signupVerifiedOk: "verify ho gaya",
    signupUsernameLabel: "Username",
    signupUsernamePh: "Username chuno",
    signupSuggested: "Suggested usernames:",
    signupPwLabel: "Password",
    signupPwPh: "Password banao",
    signupConfirmPwLabel: "Password Confirm Karo",
    signupConfirmPwPh: "Password phir se daalo",
    signupCreating: "Account ban raha hai...",
    signupCreateBtn: "Account Banao",
    signupAlreadyHave: "Account hai? Login Karo",
    signupOtpSentToast: "OTP aapke mobile par bhej diya",
    signupOtpFailToast: "OTP bhejne mein fail",
    signupTooMany: "Bahut baar try kiya. Thodi der baad try karein.",
    signupInvalidNumber: "Galat number. Format: +91XXXXXXXXXX",
    signupMobileRequired: "Mobile number zaruri hai",
    signupEnter6Otp: "6-digit OTP daalo",
    signupServerVerifyFail: "Server verification fail",
    signupMobileVerified: "Mobile verify ho gaya!",
    signupInvalidOtp: "Galat OTP. Phir check karein.",
    signupOtpExpired: "OTP expire ho gaya. Naya OTP mango.",
    signupVerifyFail: "Verification fail",
    signupUserPwRequired: "Username aur password zaruri hai",
    signupPwMismatch: "Passwords match nahi karte",
    signupPwLen: "Password kam se kam 4 character ka ho",
    signupRegFail: "Registration fail",
    signupAccountCreated: "Account ban gaya!",

    // Forgot password page
    forgotTitle: "Password Reset Karo",
    forgotSubtitle: "Password reset karne ke liye phone verify karein",
    forgotPhoneLabel: "Registered Mobile Number",
    forgotSendingOtp: "OTP bhej rahe hain...",
    forgotOtpSentTo: "OTP bheja gaya",
    forgotOtpLabel: "OTP Daalo",
    forgotOtpPh: "6-digit OTP daalo",
    forgotNewPwLabel: "Naya Password",
    forgotNewPwPh: "Naya password daalo",
    forgotResetting: "Reset ho raha hai...",
    forgotResetBtn: "Password Reset Karo",
    forgotResendBtn: "OTP Dobara Bhejo",
    forgotBackToLogin: "Login par Wapas",
    forgotOtpSentToast: "OTP aapke phone par bheja gaya",
    forgotPhoneRequired: "Phone number zaruri hai",
    forgotEnterOtp: "OTP daalo",
    forgotPwLen: "Password kam se kam 4 character ka ho",
    forgotResetFail: "Reset fail",
    forgotResetOk: "Password reset ho gaya! Login karein.",

    // Select role
    selectRoleSettingUp: "Aapka account ready ho raha hai...",

    // Customer setup
    setupTitle: "Apni Profile Pure Karo",
    setupSubtitle: "Apna customer account set karo",
    setupNameLabel: "Pura Naam *",
    setupNamePh: "Aapka naam",
    setupMobiles: "Mobile Numbers",
    setupAddMobile: "Mobile Number Add Karo",
    setupAddOther: "Aur Number Add Karo",
    setupSendOtp: "OTP Bhejo",
    setupSendingOtp: "OTP bhej rahe hain...",
    setupSentOtpTo: "OTP bheja gaya",
    setupVerify: "Verify",
    setupReferralLabel: "Referral Code (optional)",
    setupReferralPh: "Promo code daalo",
    setupSettingUp: "Set ho raha hai...",
    setupGetStarted: "Shuru Karo",
    setupNameRequired: "Naam zaruri hai",
    setupSetupFail: "Setup fail",
    setupTryAgain: "Phir try karein",
    setupPromoApplied: "Promo code apply ho gaya!",
    setupPromoInvalid: "Promo code galat hai",
    setupEnterMobile: "Mobile number daalo",
    setupNumberAlready: "Number pehle se add hai",
    setupOtpSentTo: "OTP bheja",
    setupNumberVerified: "Number verify ho gaya!",

    // Terms page
    termsPageTitle: "Terms & Conditions",
    termsPageSubtitle: "Terms, Conditions & Disclaimer",
    termsAboutLink: "Hamare Baare Mein",

    // Not found
    nfTitle: "404 Page Not Found",
    nfDesc: "Kya aap router mein page add karna bhul gaye?",
  },
};

export type TranslationKey = keyof typeof T["en"];

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "hi",
  setLang: () => {},
  t: (key) => key as string,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    try {
      const saved = localStorage.getItem("mitrify_lang_v2");
      return (saved as Language) || "hi";
    } catch {
      return "hi";
    }
  });

  const setLang = (l: Language) => {
    setLangState(l);
    try { localStorage.setItem("mitrify_lang_v2", l); } catch {}
  };

  const t = (key: TranslationKey): string => {
    return (T[lang] as any)[key] ?? (T["hl"] as any)[key] ?? (key as string);
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
