import type { CapacitorConfig } from '@capacitor/cli';

// Generated by NavBharatAI for mitrify.
const config: CapacitorConfig = {
  appId: 'com.navbharat.mitrify',
  appName: "mitrify",
  webDir: 'dist',
  // The app's background colour, chosen in NavBharatAI's App Information form.
  android: { backgroundColor: '#6366f1' },
  plugins: { SplashScreen: { backgroundColor: '#6366f1' } },
};

export default config;
