[build]
builder = "nixpacks"
buildCommand = "npm run build"

[build.variables]
NPM_CONFIG_INCLUDE = "dev"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
