import cron from "node-cron";
import nodemailer from "nodemailer";
import { storage } from "./storage";
import { getAiTokenThreshold } from "./lib/aiConfig";

const AI_WEEKLY_COST_PER_1K = 0.000125;

function makeMailer(): nodemailer.Transporter | null {
  if (!process.env.GMAIL_USER || !process.env.GMAIL_APP_PASSWORD) return null;
  return nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.GMAIL_USER,
      pass: process.env.GMAIL_APP_PASSWORD,
    },
  });
}

export async function sendAiWeeklyReport(): Promise<{ sent: boolean; error?: string }> {
  try {
    const cfg = await storage.getAiWeeklyReportConfig();
    if (!cfg.enabled || !cfg.email) {
      return { sent: false, error: "Weekly report disabled or no email configured" };
    }

    const transporter = makeMailer();
    if (!transporter) {
      console.warn("[AI Weekly Report] Gmail SMTP not configured — skipping email");
      return { sent: false, error: "Gmail SMTP not configured" };
    }

    const since = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
    const rows = await storage.getAiTokenUsageByHour(since);

    const totalTokens = rows.reduce((sum, r) => sum + r.tokens, 0);
    const peakHour = rows.reduce<{ hour: string; tokens: number } | null>((best, r) => {
      return !best || r.tokens > best.tokens ? r : best;
    }, null);

    const threshold = await getAiTokenThreshold();
    const exceededHours = rows.filter(r => r.tokens >= threshold).length;

    const estimatedCost = (totalTokens / 1000) * AI_WEEKLY_COST_PER_1K;
    const costStr = `$${estimatedCost.toFixed(4)}`;

    const weekStart = since.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
    const weekEnd = new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });

    const peakLine = peakHour
      ? `${new Date(peakHour.hour).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })} (${peakHour.tokens.toLocaleString()} tokens)`
      : "No usage recorded";

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: Arial, sans-serif; background: #f4f4f8; margin: 0; padding: 20px; }
    .card { background: #fff; border-radius: 12px; max-width: 520px; margin: 0 auto; padding: 28px 32px; box-shadow: 0 2px 10px rgba(0,0,0,0.08); }
    h2 { color: #7c3aed; margin: 0 0 4px 0; font-size: 20px; }
    .period { color: #6b7280; font-size: 13px; margin-bottom: 24px; }
    .stat { display: flex; justify-content: space-between; align-items: center; padding: 12px 0; border-bottom: 1px solid #f0f0f5; }
    .stat:last-child { border-bottom: none; }
    .label { color: #374151; font-size: 14px; }
    .value { color: #111827; font-size: 15px; font-weight: 600; }
    .badge { display: inline-block; background: #fef3c7; color: #92400e; border-radius: 6px; padding: 2px 8px; font-size: 12px; font-weight: 600; margin-left: 8px; }
    .badge.ok { background: #d1fae5; color: #065f46; }
    .footer { text-align: center; color: #9ca3af; font-size: 12px; margin-top: 24px; }
  </style>
</head>
<body>
  <div class="card">
    <h2>Mitrify AI — Weekly Cost Report</h2>
    <div class="period">${weekStart} – ${weekEnd}</div>

    <div class="stat">
      <span class="label">Total Tokens Used</span>
      <span class="value">${totalTokens.toLocaleString()}</span>
    </div>
    <div class="stat">
      <span class="label">Estimated Cost</span>
      <span class="value">${costStr}</span>
    </div>
    <div class="stat">
      <span class="label">Hourly Peak</span>
      <span class="value" style="font-size:13px">${peakLine}</span>
    </div>
    <div class="stat">
      <span class="label">Hours Exceeding Threshold <span style="font-weight:400;color:#6b7280">(${threshold.toLocaleString()} tok/hr)</span></span>
      <span class="value">
        ${exceededHours}
        <span class="badge ${exceededHours === 0 ? "ok" : ""}">${exceededHours === 0 ? "All clear" : "⚠ Review"}</span>
      </span>
    </div>

    <div class="footer">
      This report was automatically generated by Mitrify and sent to ${cfg.email}.<br/>
      Configure it in the Admin → AI tab.
    </div>
  </div>
</body>
</html>
`;

    await transporter.sendMail({
      from: `"Mitrify Admin" <${process.env.GMAIL_USER}>`,
      to: cfg.email,
      subject: `Mitrify AI Weekly Report — ${weekStart} to ${weekEnd}`,
      html,
    });

    console.log(`[AI Weekly Report] Sent to ${cfg.email} — ${totalTokens.toLocaleString()} tokens, ${costStr} est. cost`);
    return { sent: true };
  } catch (err: any) {
    console.error("[AI Weekly Report] Failed to send:", err?.message || err);
    return { sent: false, error: err?.message || String(err) };
  }
}

export function startAiWeeklyReportScheduler(): void {
  // Every Monday at 9:00 AM IST = 3:30 AM UTC (IST = UTC+5:30)
  cron.schedule("30 3 * * 1", () => {
    console.log("[AI Weekly Report] Running scheduled weekly report...");
    sendAiWeeklyReport().then(result => {
      if (!result.sent) {
        console.warn("[AI Weekly Report] Not sent:", result.error);
      }
    });
  }, { timezone: "UTC" });

  console.log("[AI Weekly Report] Scheduler registered — runs every Monday 9:00 AM IST");
}
