import cron from "node-cron";
import nodemailer from "nodemailer";
import { storage } from "./storage";
import { getAiTokenThreshold } from "./lib/aiConfig";

const AI_WEEKLY_COST_PER_1K = 0.000125;

let currentTask: ReturnType<typeof cron.schedule> | null = null;

function makeMailer(): nodemailer.Transporter | null {
  if (!process.env.GMAIL_USER || !process.env.GMAIL_APP_PASSWORD) return null;
  return nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: process.env.GMAIL_USER,
      pass: process.env.GMAIL_APP_PASSWORD,
    },
  });
}

export async function sendAiWeeklyReport(): Promise<{ sent: boolean; error?: string }> {
  try {
    const cfg = await storage.getAiWeeklyReportConfig();
    if (!cfg.enabled || !cfg.email) {
      const errMsg = "Weekly report disabled or no email configured";
      await storage.insertAiReportLog({
        recipient: cfg.email || "not set",
        success: false,
        totalTokens: 0,
        estimatedCost: "$0.0000",
        peakTokens: 0,
        exceededHours: 0,
        errorMsg: errMsg,
      }).catch(() => {});
      return { sent: false, error: errMsg };
    }

    const transporter = makeMailer();
    if (!transporter) {
      const errMsg = "Gmail SMTP not configured";
      console.warn("[AI Weekly Report] Gmail SMTP not configured — skipping email");
      await storage.insertAiReportLog({
        recipient: cfg.email,
        success: false,
        totalTokens: 0,
        estimatedCost: "$0.0000",
        peakTokens: 0,
        exceededHours: 0,
        errorMsg: errMsg,
      }).catch(() => {});
      return { sent: false, error: errMsg };
    }

    const since = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
    const rows = await storage.getAiTokenUsageByHour(since);

    const totalTokens = rows.reduce((sum, r) => sum + r.tokens, 0);
    const peakHour = rows.reduce<{ hour: string; tokens: number } | null>((best, r) => {
      return !best || r.tokens > best.tokens ? r : best;
    }, null);

    const threshold = await getAiTokenThreshold();
    const exceededHours = rows.filter(r => r.tokens >= threshold).length;

    const estimatedCost = (totalTokens / 1000) * AI_WEEKLY_COST_PER_1K;
    const costStr = `$${estimatedCost.toFixed(4)}`;

    const weekStart = since.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
    const weekEnd = new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });

    const peakLine = peakHour
      ? `${new Date(peakHour.hour).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" })} (${peakHour.tokens.toLocaleString()} tokens)`
      : "No usage recorded";

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: Arial, sans-serif; background: #f4f4f8; margin: 0; padding: 20px; }
    .card { background: #fff; border-radius: 12px; max-width: 520px; margin: 0 auto; padding: 28px 32px; box-shadow: 0 2px 10px rgba(0,0,0,0.08); }
    h2 { color: #7c3aed; margin: 0 0 4px 0; font-size: 20px; }
    .period { color: #6b7280; font-size: 13px; margin-bottom: 24px; }
    .stat { display: flex; justify-content: space-between; align-items: center; padding: 12px 0; border-bottom: 1px solid #f0f0f5; }
    .stat:last-child { border-bottom: none; }
    .label { color: #374151; font-size: 14px; }
    .value { color: #111827; font-size: 15px; font-weight: 600; }
    .badge { display: inline-block; background: #fef3c7; color: #92400e; border-radius: 6px; padding: 2px 8px; font-size: 12px; font-weight: 600; margin-left: 8px; }
    .badge.ok { background: #d1fae5; color: #065f46; }
    .footer { text-align: center; color: #9ca3af; font-size: 12px; margin-top: 24px; }
  </style>
</head>
<body>
  <div class="card">
    <h2>Mitrify AI — Weekly Cost Report</h2>
    <div class="period">${weekStart} – ${weekEnd}</div>

    <div class="stat">
      <span class="label">Total Tokens Used</span>
      <span class="value">${totalTokens.toLocaleString()}</span>
    </div>
    <div class="stat">
      <span class="label">Estimated Cost</span>
      <span class="value">${costStr}</span>
    </div>
    <div class="stat">
      <span class="label">Hourly Peak</span>
      <span class="value" style="font-size:13px">${peakLine}</span>
    </div>
    <div class="stat">
      <span class="label">Hours Exceeding Threshold <span style="font-weight:400;color:#6b7280">(${threshold.toLocaleString()} tok/hr)</span></span>
      <span class="value">
        ${exceededHours}
        <span class="badge ${exceededHours === 0 ? "ok" : ""}">${exceededHours === 0 ? "All clear" : "⚠ Review"}</span>
      </span>
    </div>

    <div class="footer">
      This report was automatically generated by Mitrify and sent to ${cfg.email}.<br/>
      Configure it in the Admin → AI tab.
    </div>
  </div>
</body>
</html>
`;

    await transporter.sendMail({
      from: `"Mitrify Admin" <${process.env.GMAIL_USER}>`,
      to: cfg.email,
      subject: `Mitrify AI Weekly Report — ${weekStart} to ${weekEnd}`,
      html,
    });

    console.log(`[AI Weekly Report] Sent to ${cfg.email} — ${totalTokens.toLocaleString()} tokens, ${costStr} est. cost`);

    await storage.insertAiReportLog({
      recipient: cfg.email,
      success: true,
      totalTokens,
      estimatedCost: costStr,
      peakTokens: peakHour?.tokens ?? 0,
      exceededHours,
    }).catch(e => console.error("[AI Weekly Report] Failed to persist log:", e?.message));

    return { sent: true };
  } catch (err: any) {
    console.error("[AI Weekly Report] Failed to send:", err?.message || err);
    // Best-effort log — don't let a log failure mask the original error
    const cfg2 = await storage.getAiWeeklyReportConfig().catch(() => ({ email: "" }));
    await storage.insertAiReportLog({
      recipient: cfg2.email || "unknown",
      success: false,
      totalTokens: 0,
      estimatedCost: "$0.0000",
      peakTokens: 0,
      exceededHours: 0,
      errorMsg: err?.message || String(err),
    }).catch(() => {});
    return { sent: false, error: err?.message || String(err) };
  } finally {
    // Auto-prune entries older than 90 days on every run (success, failure, or early exit)
    const ninetyDaysAgo = new Date(Date.now() - 90 * 24 * 60 * 60 * 1000);
    await storage.pruneOldAiReportLog(ninetyDaysAgo).catch(e => console.error("[AI Weekly Report] Failed to prune old log entries:", e?.message));
  }
}

/**
 * Build a cron expression for a given IST day and hour.
 * IST = UTC+5:30, so IST hour h:00 = UTC (h-6+24)%24:30
 */
function buildCronExpression(day: number, hour: number): string {
  const utcHour = (hour - 6 + 24) % 24;
  return `30 ${utcHour} * * ${day}`;
}

/**
 * Stop any existing scheduler and start a new one with the given day/hour (IST).
 */
export function rescheduleAiWeeklyReport(day: number, hour: number): void {
  if (currentTask) {
    currentTask.stop();
    currentTask = null;
  }

  const expr = buildCronExpression(day, hour);
  const DAY_NAMES = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];
  const dayName = DAY_NAMES[day] ?? `day ${day}`;

  currentTask = cron.schedule(expr, () => {
    console.log("[AI Weekly Report] Running scheduled weekly report...");
    sendAiWeeklyReport().then(result => {
      if (!result.sent) {
        console.warn("[AI Weekly Report] Not sent:", result.error);
      }
    });
  }, { timezone: "UTC" });

  console.log(`[AI Weekly Report] Scheduler registered — runs every ${dayName} at ${hour}:00 IST (cron: ${expr})`);
}

export async function startAiWeeklyReportScheduler(): Promise<void> {
  const cfg = await storage.getAiWeeklyReportConfig();
  rescheduleAiWeeklyReport(cfg.sendDay, cfg.sendHour);
}
